# timestep
dt: 0.002
# max temperature heating phase 1 in K
temp1: 100.0
# heating time for phase 1
heat_time1: 100.0
# max temperature heating phase 2 in K
temp2: 300.0
# heating time for phase 2 (from time=0 to temp2)
heat_time2: 500.0
# total time for each heating run in ps (must be larger than heat_time1 + heat_time2)
total_heat_time: 2000.0
# nonbonded cutoff distance
cut: 10.0
# restraint weight for heating run in kcal/mol
restraint: 10.0