# number of minimization runs to perform
n_min_runs: 7
# number of steepest descent steps to perform before switching to conjugate gradient
ncyc: 1000 
# total number of minimization steps to perform
maxcyc: 5000 
# nonbonded cutoff distance
cut: 10.0
# restraint weight for each minimization run in kcal/mol, should have the same length as n_min_runs
restraint: [10.0, 5.0, 2.0, 1.0, 0.5, 0.1, 0.0] 